[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
advent-of-code-common = {path = "../common"}
image = "0.25.5"
nom = "7.1.3"
rayon = "1.10.0"
